# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening your first issue here! Your contribution is welcomeğŸ™. Make sure to follow the code of conduct!
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: > 
  Thanks for opening this pull request! Make sure you have read the contributing guidelines, assigned an respective issue (if applicable) to this PR ğŸ˜‡
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull requestğŸ‰! We are proud of you!
