comment:
  footer: |-
    ----
    > *This is an automated response created by a **GitHub Action***
    > *Mentioning the user won't have any effect!*

# Send a Comment when the PR was (un)labeled with the "Status: Ready" label
labels:
  - name: 'Status: Ready'
    labeled:
      pr:
        body: |-
          The Pull request of @{{ pull_request.user.login }} has been marked as **Ready**!
          
          It can now be reviewed and/or merged by Maintainers.
        draft: false
    unlabeled:
      pr:
        body: |-
          The Pull request of @{{ pull_request.user.login }} is **no longer marked as Ready**!
          
          Maintainers should wait with merging the Pull request until it is marked as ready again.
        draft: true
  - name: 'Type: invalid'
    labeled:
      issue:
        body: |-
          Hello @{{ issue.user.login }},
          
          Your Issue has been marked as **Invalid** and was automatically closed.
          To get it re-opened, make sure to follow our [Contributing Guidelines](https://github.com/Readme-Workflows/recent-activity/blob/main/.github/CONTRIBUTING.md) and update your Issue accordingly.
        action: close
      pr:
        body: |-
          Hello @{{ pull_request.user.login }},
          
          Your Pull request has been marked as **Invalid** and was automatically closed.
          To get it re-opened, make sure to follow our [Contributing Guidelines](https://github.com/Readme-Workflows/recent-activity/blob/main/.github/CONTRIBUTING.md) and update your Pull request accordingly.
        action: close
    unlabeled:
      issue:
        body: |-
          Thank you for following our [Contributing Guidelines](https://github.com/Readme-Workflows/recent-activity/blob/main/.github/CONTRIBUTING.md) @{{ issue.user.login }}!
          
          Your Issue is **no longer marked as Invalid**.
        action: open
      pr:
        body: |-
          Thank you for following our [Contributing Guidelines](https://github.com/Readme-Workflows/recent-activity/blob/main/.github/CONTRIBUTING.md) @{{ pull_request.user.login }}!
          
          Your Pull request is **no longer marked as Invalid**.
        action: open
  - name: 'Type: duplicate'
    labeled:
      issue:
        body: |-
          Hello @{{ issue.user.login }},
          
          Your Issue has been marked as **Duplicate** which means that an issue with the same Feature request or Bug report already exists.
          Please check for already existing issues next time.
        action: close
      pr:
        body: |-
          Hello @{{ pull_request.user.login }},
          
          Your Pull request has been marked as **Duplicate** which means that a Pull request with the same changes already exists.
          Please check for already existing Pull requests next time.
        action: close
